backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "src/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:

# blogs fields
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["fullname"]
        value_field: "fullname"
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "tags"
        widget: "list"
        name: "tags"
        add_to_top: true
        allow_add: true
  
# authors fields
  - label: "Authors"
    name: "authors"
    folder: "src/authors"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "fullname", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}

  
# page fields

  - label: "Pages"
    name: "pages"
    create: true
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "metaDescription", widget: "string" }
          - { label: "Meta Image" , name: "metaImage", widget: "image" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Draft", name: "draft", widget: "boolean", default: true }
          - { label: "Hero Carousel",name: "heroCarousel",widget: "list",summary: '{{fields.image}}',field: {label: Image, name: image, widget: image} }

      - label: "About"
        name: "about"
        file: "src/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "metaDescription", widget: "string" }
          - { label: "Meta Image" , name: "metaImage", widget: "image" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {label: "Draft", name: "draft", widget: "boolean", default: true}

# products fields  
  
  - label: "Products"
    name: "products"
    folder: "src/products"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["fullname"]
        value_field: "fullname"
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Specifications", name: "specifications", widget: "markdown" }
      - label: "tags"
        widget: "list"
        name: "tags"
        add_to_top: true
        allow_add: true
      - widget: "image"
        label: "Thumbnail"
        name: "thumbnail"
        media_library:
          config:
            multiple: false
      - label: "Hero Image"
        name: "heroImage"
        widget: "image"
        media_library:
          config:
            multiple: false

      - label: "Product Images"
        name: "productImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}

# announcements fields

  - label: "Announcements"
    name: "announcements"
    folder: "src/announcements"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Description", name: "metaDescription", widget: "string" }
      - { label: "Meta Image" , name: "metaImage", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }

# jobs fields

  - label: "Jobs"
    name: "jobs"
    folder: "src/jobs"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Thumbnail Image"
        name: "thumbnailImage"
        widget: "image"
        media_library:
          config:
            multiple: false

# news fields
  - label: "News"
    name: "news"
    folder: "src/news"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["name.first"]
        value_field: "name.first"
      - label: "tags"
        widget: "list"
        name: "tags"
        add_to_top: true
        allow_add: true
      - label: "Thumbnail Image"
        name: "thumbnailImage"
        widget: "image"
        media_library:
          config:
            multiple: false
      - label: "Hero Image"
        name: "heroImage"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { label: "Body", name: "body", widget: "markdown" }

# navigation settings

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
  